/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ADropdownButton: typeof import('ant-design-vue/es')['DropdownButton']
    AInput: typeof import('ant-design-vue/es')['Input']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutFooter: typeof import('ant-design-vue/es')['LayoutFooter']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    ATabPane: typeof import('ant-design-vue/es')['TabPane']
    ATabs: typeof import('ant-design-vue/es')['Tabs']
    Build: typeof import('./src/components/svg/Build.vue')['default']
    ContentTitle: typeof import('./src/components/ContentTitle.vue')['default']
    EditWrapper: typeof import('./src/components/EditWrapper.vue')['default']
    HTML5: typeof import('./src/components/svg/HTML5.vue')['default']
    ImageTabIcon: typeof import('./src/components/svg/ImageTabIcon.vue')['default']
    Light: typeof import('./src/components/svg/Light.vue')['default']
    LogoIcon: typeof import('./src/components/svg/LogoIcon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShapeTabIcon: typeof import('./src/components/svg/ShapeTabIcon.vue')['default']
    TemplateList: typeof import('./src/components/templateList/TemplateList.vue')['default']
    TextTabIcon: typeof import('./src/components/svg/TextTabIcon.vue')['default']
  }
}
